#!/bin/bash

function loadOne {
    local LOADER="$1"
    local DB="$2"
    local FILE="$3"

    rm -rf "$DB"/*
    time dev tdb2.tdbloader --loader=$LOADER --loc $DB $FILE
}

function between() {
    echo
    echo "------------------"
    echo
}

mkdir -p DBX

DATA="$HOME/Datasets/BSBM/bsbm-200m.nt.gz"

loadOne phased DBX "$DATA"

between

loadOne phased DBX "$DATA"

#rm -rf DBX/*
